runzip: fix build
Configure script produces a cryptic message:

```
configure:4540: error: ZLIB version too old, please install at least v1.1.2
```

It's actually misleading and comes from the vendored libzip 0.7.1 configure check.
It fails due to do `-Wimplicit-int`:

```
conftest.c:16:16: error: type defaults to 'int' in declaration of 'unzOpen' [-Wimplicit-int]
   16 | extern ZEXPORT unzOpen (const char *path);
```

Vendored libzip is pretty heavily modified and unvendoring seems impossible.
Furthermore, libzip from nixpkgs in buildInputs
is actually unused and can be dropped - only zlib is necessary.